services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Portas que o mundo vÃª
      - '80:80'
      - '443:443'
      # Porta do Painel de Controle (Admin)
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - net_public

networks:
  net_public:
    driver: bridge